### ISSUE TITLE
International phone numbers are not permitted

### ISSUE THREAD

**Issue by Riscky** [svsticky/constipated-koala#487]
### Expected behaviour
An international student wants to sign up on the intro.svsticky.nl page and enters his phone number.
Everything goes well and the student is signed up.

### Actual behavior
The students enters his (international) phone number and gets an error on clicking submit.
An admin cannot set an non 10-digit phone number either

**Comment by FInnvos123** [comment]
The regex used to verify phone numbers doesn't actually verify phone numbers. (0123456789 and 00000000000 are valid phone numbers according to koala)

Because of this there are now multiple formats in the database:
- 06  [rest of number]
- 00  [country code]  [rest of number]
- 00000000000 (yes, some people signed up with this phone number)
- some other format we haven't found

I've been working on phone number validation with [telephone_number](https://github.com/mobi/telephone_number), now all new phone numbers will be saved in a standard format:
`+[country code][rest of number]`

Now we just need to convert all existing numbers to the new format.
