### ISSUE TITLE
Fix checkbox of "inschrijfbaar"

### ISSUE THREAD

**Issue by Jelte-Akker** [svsticky/constipated-koala#904]
### Expected behaviour
We want to see the checkbox of "inschrijfbaar" checked after the activity has been opened automatically. So boardmembers also see it has been opened.

### Actual behavior
The checkbox of the "inschrijfbaar" does not get checked when the activity is opened automatically

**Comment by Riscky** [comment]
In my opinion an activity that is not enrollable should also not be enrollable after the open time.
Otherwise the checkbox does only work till the open time, and its status is after that governed by the open time.
So instead of changing the checkbox to reflect the status of `open` instead of `enrollable`, we should change the definition of `open`:

https://github.com/svsticky/constipated-koala/blob/b213d2f679ecc12e0576f27be1d9690f0f09b9f3/app/models/activity.rb#L190-L192

Line 191 should then be something like:
`return is_enrollable && ((!open_date.present? && !open_time.present?) || DateTime.now > when_open))`
